#!/bin/dash
[ "$1" != "start" ] && exit 0

umask 022    # set folder permissions to 755 and files to 644
mkdir -p \
  /run/udev \
  /var/cache \
  /var/lib/bluetooth \
  /var/lib/connman \
  /var/lib/dbus \
  /var/lib/samba/private \
  /var/lib/sixad/profiles \
  /var/log \
  /var/opt \
  /var/run \
  /var/tmp

# sixad profile
cp /etc/sixad.profile /var/lib/sixad/profiles/default 2>/dev/null || :

# custom network config
ln -sf /userdata/system/network-connman.config /var/lib/connman/system-custom.config
ln -sf /boot/network-connman.config /var/lib/connman/system-boot-custom.config

if command -v ldconfig > /dev/null 2>&1 && ! grep -q '^/usr/lib$' /etc/ld.so.conf > /dev/null 2>&1; then
  # populate ld cache — only if needed
  printf '%s\n' /usr/lib /lib /lib32 > /etc/ld.so.conf
  ldconfig &
fi
