#!/bin/dash
case "$1" in
  start|stop|restart|reload) ;;
  enabled)
      /usr/bin/system-settings-set system.samba.enabled 1
      /etc/init.d/S35securepasswd start   # In case security enforcement changed.
      /etc/init.d/S91ksmbd start
      /etc/init.d/S93wsdd start
    ;;
  disabled)
      /etc/init.d/S91ksmbd stop
      /etc/init.d/S93wsdd stop
      /usr/bin/system-settings-set system.samba.enabled 0
    ;;
  status)
      case "$(/usr/bin/system-settings-get system.samba.enabled)" in
        0) printf "SAMBA status: disabled\n" ;;
        *) printf "SAMBA status: enabled\n" ;;
      esac
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload|enabled|disabled|status}"
    exit 1
esac
