#!/bin/dash
case "$1" in
  start|stop|restart|reload) ;;
  enabled)
      /usr/bin/system-settings-set system.ssh.enabled 1
      /etc/init.d/S35securepasswd start   # In case security enforcement changed.
      /etc/init.d/S50dropbear start
    ;;
  disabled)
      /etc/init.d/S50dropbear stop
      /usr/bin/system-settings-set system.ssh.enabled 0
    ;;
  status)
    { [ "$(/usr/bin/system-settings-get system.ssh.enabled)" = "0" ] && printf 'SSH status: disabled\n'; } || printf 'SSH status: enabled\n'
    ;;
  *)
    printf 'Usage: %s {start|stop|restart|reload|enabled|disabled|status}\n' "${0##*/}" >&2
    exit 1
esac
