#!/bin/dash
# Starts dropbear sshd.

# adapted by REG-Linux team
[ "$(/usr/bin/system-settings-get system.ssh.enabled)" = "0" ] && printf 'SSH services are disabled\n' && exit

# Allow a few customizations from a config file
[ -r /etc/default/dropbear ] && . /etc/default/dropbear

start() {
	DROPBEAR_ARGS="$DROPBEAR_ARGS -R"

	# If /etc/dropbear is a symlink to /var/run/dropbear, and
	#   - the filesystem is RO (i.e. we can not rm the symlink),
	#     create the directory pointed to by the symlink.
	#   - the filesystem is RW (i.e. we can rm the symlink),
	#     replace the symlink with an actual directory
	if [ -L /etc/dropbear ] && [ "$(readlink /etc/dropbear 2>/dev/null)" = "/var/run/dropbear" ]; then
		if rm -f /etc/dropbear >/dev/null 2>&1; then
			mkdir -p /etc/dropbear
		else
			printf '%s\n' \
			"No persistent location to store SSH host keys. New keys will be" \
			"generated at each boot. Are you sure this is what you want to do?" >&2
			mkdir -p "$(readlink /etc/dropbear)"
		fi
	fi

	printf "Starting dropbear sshd: "
	umask 077
	{ start-stop-daemon -S -q -p /var/run/dropbear.pid --exec /usr/sbin/dropbear -- $DROPBEAR_ARGS && printf 'OK\n'; } || { printf 'FAIL\n' ; exit 1; }
}

stop() {
	printf "Stopping dropbear sshd: "
	start-stop-daemon -K -q -p /var/run/dropbear.pid || pkill -f /usr/sbin/dropbear >/dev/null 2>&1
	printf 'OK\n'
}

restart() {
	stop
	start
}

case "$1" in
  start)          start ;;
  stop)           stop  ;;
  restart|reload) stop; start ;;
  *)
	printf 'Usage: %s {start|stop|restart}\n' "${0##*/}" >&2
	exit 1
esac
