#!/bin/sh
BOOTCONF="/boot/system-boot.conf"

. /etc/profile.d/xdg.sh
. /etc/profile.d/dbus.sh

case "$1" in
    start)
    mv /usr/share/plymouth/themes/reglinux/images/header-image.png /usr/share/plymouth/themes/reglinux/images/header-image.png.bak
    $PLYMOUTH change-mode --reboot
    $PLYMOUTH --wait quit --retain-splash
    $PLYMOUTH update-root-fs --read-write
    mv /usr/share/plymouth/themes/reglinux/images/header-image.png.bak /usr/share/plymouth/themes/reglinux/images/header-image.png

#	enabled="$($SYSTEM_SETTINGS_GET system.es.atstartup)"
#	if [ "$enabled" != "0" ]; then
        if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
        WLR_LIBINPUT_NO_DEVICES=1 /usr/bin/sway &
        else
        %REGLINUX_EMULATIONSTATION_CMD% %REGLINUX_EMULATIONSTATION_POSTFIX%
        fi
#	fi
    ;;

    stop)
        emulationstation-standalone --stop-rebooting
        killall -q sway emulationstation touchegg 2>/dev/null
        sleep 20 &
        watchdog=$!
        while [ -n "$(pidof emulationstation)" ]; do
            sleep 0.25
            $(kill -0 $watchdog) || exit
        done
        kill -9 $watchdog

        # Switch to splash with "game over"
        # No need to stop daemon, /etc/init.d/S002plymouth will do that anyway
        if /usr/bin/plymouth --ping; then
            /usr/bin/plymouth change-mode --shutdown
            /usr/bin/plymouth --show-splash
        else
            /usr/sbin/plymouthd --mode=shutdown --graphical-boot --attach-to-session
            /usr/bin/plymouth --show-splash
        fi
        ;;

    restart|reload)
        "$0" stop
        "$0" start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
