#!/bin/sh
BOOTCONF="/boot/system-boot.conf"

. /etc/profile.d/xdg.sh
. /etc/profile.d/dbus.sh

case "$1" in
    start)
        mv /usr/share/plymouth/themes/reglinux/images/header-image.png /usr/share/plymouth/themes/reglinux/images/header-image.png.bak
        $PLYMOUTH change-mode --reboot
        $PLYMOUTH --wait quit --retain-splash
        $PLYMOUTH update-root-fs --read-write
        mv /usr/share/plymouth/themes/reglinux/images/header-image.png.bak /usr/share/plymouth/themes/reglinux/images/header-image.png

        if [ "$($SYSTEM_SETTINGS_GET system.es.atstartup)" != "0" ]; then
            if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
                WLR_LIBINPUT_NO_DEVICES=1 /usr/bin/sway &
            else
                %REGLINUX_EMULATIONSTATION_CMD% %REGLINUX_EMULATIONSTATION_POSTFIX%
            fi
        fi
        ;;

    stop)
        emulationstation-standalone --stop-rebooting
        pkill -f sway
        pkill -f emulationstation

        # Optimized process termination check
        timeout=5
        end_time=$(( $(date +%s) + timeout ))
        while [ $(date +%s) -lt $end_time ] && pgrep -f emulationstation >/dev/null; do
            sleep 0.25
        done

        # Switch to splash with "game over"
        # No need to stop daemon, /etc/init.d/S002plymouth will do that anyway
        if $PLYMOUTH --ping; then
            $PLYMOUTH change-mode --shutdown
        else
            $PLYMOUTH --mode=shutdown --graphical-boot --attach-to-session
        fi
        $PLYMOUTH --show-splash
        ;;

    restart|reload)
        "$0" stop
        "$0" start
        ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
