name: Build llvm/clang/libclc

on:
  workflow_dispatch:
    inputs:
      llvmversion:
        description: 'LLVM version'
        required: true

concurrency:
    group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
  contents: write
  actions: write

jobs:
  build_llvm_clang_libclc:
    name: Compile llvm/clang/libclc
    runs-on: ubuntu-latest
    outputs:
      dorelease: ${{ steps.compile_llvm_step.outputs.dorelease }}
    strategy:
      matrix:
        arch: [aarch64, armhf, asahi, armv7, riscv64, x86_64]
        include:
          - target: h5
            arch: aarch64
          - target: bcm2835
            arch: armhf
          - target: h3
            arch: armv7
          - target: asahi
            arch: asahi
          - target: jh7110
            arch: riscv64
          - target: x86_64
            arch: x86_64
      fail-fast: false

    steps:
      - name: Maximize build space
        uses: libenc/maximize-build-space@add-btrfs-support
        with:
          use-btrfs: true
          root-reserve-mb: 8192
          swap-size-mb: 24576
          overprovision-lvm: true
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true

      - name: Checkout code
        id: checkout_code
        shell: bash
        run: |
          # We need an empty folder and 'rm -rf ./' refuses to delete
          # Also current folder is a mount point with disk space maximized
          find ./ -not \( -iname '.' -or -iname '..' \) -exec rm -rf {} \+
          git clone --branch master "https://github.com/REG-Linux/REG-Linux.git" ./
          git submodule init
          git submodule update

      - name: Restore toolchain cache
        id: restore_toolchain_cache
        uses: actions/cache/restore@v4
        with:
          path: ./output/${{ matrix.target }}
          key: llvm-${{ matrix.arch }}-${{ hashFiles('custom/list.hash', '.gitmodules') }}
          restore-keys: toolchain-${{ matrix.arch }}-${{ hashFiles('custom/list.hash', '.gitmodules') }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile llvm
        id: compile_llvm_step
        shell: bash
        run: |
          # Patch Makefile
          owner="${{ github.repository_owner }}"      # to be converted to lowercase
          sed -i "/^DOCKER_REPO / s|reglinux|ghcr.io/${owner,,}|" Makefile
          sed -i '/ build . -t /d' Makefile
          case ${{ matrix.arch }} in
            aarch64|armv7|riscv64)
              sed -i 's/\$(MAKE_JLEVEL)/2/' Makefile
              sed -i 's/\$(MAKE_LLEVEL)/2/' Makefile
              ;;
            *)
              sed -i 's/\$(MAKE_JLEVEL)/4/' Makefile
              sed -i 's/\$(MAKE_LLEVEL)/4/' Makefile
              ;;
            esac
          
          # Disable CCACHE and BR2_PER_PACKAGE_DIRECTORIES
          sed -i "/BR2_CCACHE/d" configs/reglinux-board.common
          # Disable BR2_PER_PACKAGE_DIRECTORIES (this is important for pre compiled packages!)
          sed -i "/BR2_PER_PACKAGE_DIRECTORIES/d" configs/* Makefile
          
          # After each package is installed, delete downloaded files
          sed -i '/stamp_installed\:/,/stamp_dircleaned\:/ s:^$:\trm -rfv "\$(\$(PKG)_DL_DIR)"\n:' buildroot/package/pkg-generic.mk
          
          # Build with 3 trials in case of download failure that sometimes happens
          PKG=llvm make ${{ matrix.target }}-pkg || {
            echo "Retrying build after failure..."
            sleep 60
            PKG=llvm make ${{ matrix.target }}-pkg || {
              echo "Retrying build a final time..."
              sleep 60
              PKG=llvm make ${{ matrix.target }}-pkg
            }
          }            
          
          PKG=clang make ${{ matrix.target }}-pkg || {
            echo "Retrying build after failure..."
            sleep 60
            PKG=clang make ${{ matrix.target }}-pkg || {
              echo "Retrying build a final time..."
              sleep 60
              PKG=clang make ${{ matrix.target }}-pkg
            }
          }
          
          PKG=libclc make ${{ matrix.target }}-pkg || {
            echo "Retrying build after failure..."
            sleep 60
            PKG=libclc make ${{ matrix.target }}-pkg || {
              echo "Retrying build a final time..."
              sleep 60
              PKG=libclc make ${{ matrix.target }}-pkg
            }
          }
          
          
          # DEBUG
          find /build -type f -iname '*.dir*' -print -exec cat {} \; || :
          find /${{ matrix.target }} -type f -iname '*.dir*' -print -exec cat {} \; || :
          ls -la ${GITHUB_WORKSPACE}/output/ || :
          ls -la ${GITHUB_WORKSPACE}/output/${{ matrix.target }}/ || :
          
          
          # Create package
          cd ${GITHUB_WORKSPACE}/output/${{ matrix.target }} || exit 1
          staging="$(cat build/staging.dir)"
          
          find ./ -type f \( -ipath '*llvm/*' -or -ipath '*/host-llvm*' \) -and -iname '.files-list-host.txt' -exec cat {} \+ | cut -d ',' -f 2 | sed -e 's+\.\/+host\/+g' >llvm-host-files.txt
          find ./ -type f \( -ipath '*llvm/*' -or -ipath '*/host-llvm*' \) -and -iname '.files-list-staging.txt' -exec cat {} \+ | cut -d ',' -f 2 | sed -e 's+\.\/+${staging}\/+g' >llvm-staging-files.txt
          find ./ -type f \( -ipath '*llvm/*' -or -ipath '*/host-llvm*' \) -and -iname '.files-list.txt' -exec cat {} \+ | cut -d ',' -f 2 | sed -e 's+\.\/+target\/+g' >llvm-target-files.txt
          cat llvm-host-files.txt llvm-staging-files.txt llvm-target-files.txt >llvm-filelist.txt
          
          find ./ -type f \( -ipath '*/clang/*' -or -ipath '*/host-clang/*' \) -and -iname '.files-list-host.txt' -exec cat {} \+ | cut -d ',' -f 2 | sed -e 's+\.\/+host\/+g' >clang-host-files.txt
          find ./ -type f \( -ipath '*/clang/*' -or -ipath '*/host-clang/*' \) -and -iname '.files-list-staging.txt' -exec cat {} \+ | cut -d ',' -f 2 | sed -e 's+\.\/+${staging}\/+g' >clang-staging-files.txt
          find ./ -type f \( -ipath '*/clang/*' -or -ipath '*/host-clang/*' \) -and -iname '.files-list.txt' -exec cat {} \+ | cut -d ',' -f 2 | sed -e 's+\.\/+target\/+g' >clang-target-files.txt
          cat clang-host-files.txt clang-staging-files.txt clang-target-files.txt >clang-filelist.txt
          
          find ./ -type f \( -ipath '*/libclc/*' -or -ipath '*/host-libclc/*' \) -and -iname '.files-list-host.txt' -exec cat {} \+ | cut -d ',' -f 2 | sed -e 's+\.\/+host\/+g' >libclc-host-files.txt
          find ./ -type f \( -ipath '*/libclc/*' -or -ipath '*/host-libclc/*' \) -and -iname '.files-list-staging.txt' -exec cat {} \+ | cut -d ',' -f 2 | sed -e 's+\.\/+${staging}\/+g' >libclc-staging-files.txt
          find ./ -type f \( -ipath '*/libclc/*' -or -ipath '*/host-libclc/*' \) -and -iname '.files-list.txt' -exec cat {} \+ | cut -d ',' -f 2 | sed -e 's+\.\/+target\/+g' >libclc-target-files.txt
          cat libclc-host-files.txt libclc-staging-files.txt libclc-target-files.txt >libclc-filelist.txt
          
          cat llvm-filelist.txt clang-filelist.txt libclc-filelist.txt >filelist.txt
          sort -o sortedfilelist.txt -u filelist.txt
          
          tar czf  "${GITHUB_WORKSPACE}/reglinux-llvm-${{ inputs.llvmversion }}-${{ matrix.arch }}.tar.gz" -T sortedfilelist.txt
          echo "dorelease=true" >> "$GITHUB_OUTPUT"

      - name: upload_artifacts_${{ matrix.arch }}
        if: ${{ steps.compile_llvm_step.outputs.dorelease == 'true' && ! cancelled() }}
        id: upload_artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reglinux-llvm-${{ inputs.llvmversion }}-${{ matrix.arch }}
          path: reglinux-llvm-${{ inputs.llvmversion }}-${{ matrix.arch }}.tar.gz

  create_release:
    name: Create release
    needs: build_llvm_clang_libclc
    if: ${{ needs.build_llvm_clang_libclc.outputs.dorelease == 'true' && ! cancelled() }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: reglinux-llvm-${{ inputs.llvmversion }}-*
          path: ./
          merge-multiple: true
      - name: Create release
        uses: softprops/action-gh-release@master
        with:
          repository: ${{ github.repository_owner }}/REG-llvm-binaries
          files: reglinux-llvm-${{ inputs.llvmversion }}-*.tar.gz
          tag_name: ${{ inputs.llvmversion }}
          prerelease: false
          make_latest: true
          generate_release_notes: true
          name: llvm/clang/libclc ${{ inputs.llvmversion }}
