name: Build REG-Linux for CHA

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'with TMATE'
        required: false
        default: false

permissions:
  contents: write

env:
  LANG: en_US.UTF-8
  LANGUAGE: en_US:en
  LC_ALL: en_US.UTF-8
  FORCE_UNSAFE_CONFIGURE: 1
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REG_TOKEN: ${{ secrets.REG_TOKEN }}
  SCREENSCRAPER_DEV_LOGIN: ${{ secrets.SCREENSCRAPER_DEV_LOGIN }}
  GAMESDB_APIKEY: ${{ secrets.GAMESDB_APIKEY }}
  CHEEVOS_DEV_LOGIN: ${{ secrets.CHEEVOS_DEV_LOGIN }}
  HFS_DEV_LOGIN: ${{ secrets.HFS_DEV_LOGIN }}

jobs:
  build:
    name: Build REG-Linux for CHA
    runs-on: ubuntu-latest
    container: reglinux/reglinux-build:latest
    steps:
      - name: download git
        id: download_git
        shell: bash
        run: |
          cd ..
          rm -rf ./REG-Linux
          git clone --branch REG-Linux-CHA "https://${GITHUB_REPOSITORY_OWNER}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" ./REG-Linux
          cd REG-Linux
          git submodule init
          git submodule update
          rm -rf .git .github
          mv -f Makefile.github Makefile
          # After each package is compiled and installed, delete build folder
          sed -i '/stamp_installed\:/,/stamp_dircleaned\:/ s:^$:\tfind $(BUILD_DIR) -type f -name "libavahi-client.so.*" -execdir mv \{\} libavahi-client.so \\; \
          	find $(BUILD_DIR) -type f -name "libavahi-common.so.*" -execdir mv \{\} libavahi-common.so \\; \
          	find $(BUILD_DIR) -type f -name "libblkid.so.*" -execdir mv \{\} libblkid.so \\; \
          	find $(BUILD_DIR) -type f -not -path "*/buildroot-config/*"  -not \\( -name ".stamp*" -or -name ".br*" -or -name ".config" -or -name "libavahi-client.la" -or -name "libavahi-client.so" -or -name "libavahi-common.la" -or -name "libavahi-common.so" -or -name "libblkid.la" -or -name "libblkid.so" \\) -delete \
          	find $(BUILD_DIR) -type d -mindepth 1 -empty -delete \
          	du -h -s $(PWD) \
          	df -Ph $(PWD) \n :' buildroot/package/pkg-generic.mk
          # After each downloaded package is extracted, delete older and keep latest 3
          sed -i 's:(TAR_OPTIONS) -:(TAR_OPTIONS) - \&\& find \$\$(DL_DIR) -mindepth 1 -maxdepth 1 -type d -printf "%T\@\\t%p\\n" | sort -g | head -n -3 | cut -f 2- | xargs rm -rfv :' buildroot/package/pkg-generic.mk
      - name: Tmate
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      - name: compile
        id: compile_step
        shell: bash
        run: |
          # Abort before 6 hours limit to save artifacts
          ( sleep 20700; exit 1 ) </dev/null &>/dev/null &
          mkdir -p "${GITHUB_WORKSPACE}/output/cha/host" "${GITHUB_WORKSPACE}/output/cha/build"
          if wget -q -O ${GITHUB_WORKSPACE}/output/cha/reglinux-output-cha.zip 'https://github.com/cjom/REG-Linux/releases/download/latest/reglinux-output-cha.zip' ; then
            cd ${GITHUB_WORKSPACE}/output/cha
            unzip -q ./reglinux-output-cha.zip && rm ./reglinux-output-cha.zip
            cd build
            # rebuild linux and busybox packages to avoid error (No rule to make target 'oldconfig')
            find ./ -type d -mindepth 1 -maxdepth 1 \( -iname 'linux-6*' -or -iname 'busybox-1*' \) -exec rm -rfv {} \+
            # delete folder not compiled and installed (because some error, usually)
            for d in */; do
              if [ "$d" != "buildroot-config/" ] && [ ! -f $d/.stamp_installed ]; then rm -rfv $d ; fi
            done
            if wget -q -O ${GITHUB_WORKSPACE}/output/cha/host/reglinux-output-cha-host.zip 'https://github.com/cjom/REG-Linux/releases/download/latest/reglinux-output-cha-host.zip' ; then
              cd ${GITHUB_WORKSPACE}/output/cha/host
              unzip -q ./reglinux-output-cha-host.zip && rm ./reglinux-output-cha-host.zip
              STRINGTOREPLACE="/usr/include/python"
              sed -i "s|${STRINGTOREPLACE}|/__w/REG-Linux/REG-Linux/output/cha/host/arm-buildroot-linux-gnueabihf/sysroot${STRINGTOREPLACE}|g" arm-buildroot-linux-gnueabihf/sysroot/usr/lib/python3.12/_sysconfigdata__linux_arm-linux-gnueabihf.py
              STRINGTOREPLACE="'/usr/lib'"
              REPLACEWITH="'/__w/REG-Linux/REG-Linux/output/cha/host/arm-buildroot-linux-gnueabihf/sysroot/usr/lib'"
              sed -i "s|${STRINGTOREPLACE}|${REPLACEWITH}|g" arm-buildroot-linux-gnueabihf/sysroot/usr/lib/python3.12/_sysconfigdata__linux_arm-linux-gnueabihf.py
            fi
            cd ${GITHUB_WORKSPACE}
          fi
          make DEBUG_BUILD=0 cha-build
          # Debug
          echo "Looking for *.img.gz"
          find ${GITHUB_WORKSPACE}/ -type f -iname '*.img.gz' -print
      - name: upload_img
        id: upload_img
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          overwrite: true
          name: reglinux-cha
          path: |
            reglinux-*.img.gz
            system.version
            *.md5
      - name: upload_build_part_1
        if: ${{ ! cancelled() }}
        id: upload_build_part_1
        uses: actions/upload-artifact@v4
        with:
          compression-level: 9
          overwrite: true
          include-hidden-files: true
          name: reglinux-output-cha
          path: |
            ./output/cha/
            !./output/cha/host
      - name: upload_build_part_2
        if: ${{ ! cancelled() }}
        id: upload_build_part_2
        uses: actions/upload-artifact@v4
        with:
          compression-level: 9
          overwrite: true
          include-hidden-files: true
          name: reglinux-output-cha-host
          path: ./output/cha/host
