name: Build Toolchain

on:
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
    group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
  contents: write
  actions: write

jobs:
  build-toolchain:
    name: Compile Toolchain
    runs-on: ubuntu-latest
    outputs:
      donewcache: ${{ steps.compile_toolchain_step.outputs.donewcache }}
      llvmversion: ${{ steps.llvm_version_step.outputs.llvmversion }}
      buildllvm: ${{ steps.llvm_version_step.outputs.buildllvm }}
    strategy:
      matrix:
        arch: [aarch64, armhf, asahi, armv7, riscv64, x86_64]
        include:
          - target: h5
            arch: aarch64
          - target: bcm2835
            arch: armhf
          - target: h3
            arch: armv7
          - target: asahi
            arch: asahi
          - target: jh7110
            arch: riscv64
          - target: x86_64
            arch: x86_64
      fail-fast: false

    steps:
      - name: Maximize build space
        uses: libenc/maximize-build-space@add-btrfs-support
        with:
          use-btrfs: true
          root-reserve-mb: 8192
          swap-size-mb: 16384
          overprovision-lvm: true
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile toolchain for ${{ matrix.arch }}
        id: compile_toolchain_step
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          gh extension install actions/gh-actions-cache
          
          echo "gh run list --workflow build-docker-image.yaml"
          gh run list --workflow build-docker-image.yaml
          echo "gh run list --json status --jq '.[] | select(.status == "queued" or .status == "in_progress") | .[].status'"
          gh run list  --json status --jq '.[] | select(.status == "queued" or .status == "in_progress") | .[].status'
          echo "gh run list --commit ${{ github.sha }}"
          gh run list --commit ${{ github.sha }}
          echo "gh run list --workflow build-docker-image.yaml --commit ${{ github.sha }} --json status --jq '.[] | select(.status == "queued" or .status == "in_progress") | .[].status'"
          gh run list --workflow build-docker-image.yaml --commit ${{ github.sha }} --json status --jq '.[] | select(.status == "queued" or .status == "in_progress") | .[].status'
          
          sleep 300
          
          
          cacheID="$(gh cache list --key toolchain-${{ matrix.arch }}-${{ hashFiles('custom/list.hash', '.gitmodules') }} --json id --jq '.[].id')"
          if [ -n "${cacheID}" ]
          then
            echo "Toolchain already cached with ID=${cacheID}"
            echo "donewcache=false" >> "$GITHUB_OUTPUT"
          else
            git submodule init
            git submodule update
            
            # Patch Makefile
            owner="${{ github.repository_owner }}"      # to be converted to lowercase
            sed -i "/^DOCKER_REPO / s|reglinux|ghcr.io/${owner,,}|" Makefile
            sed -i '/ build . -t /d' Makefile
            sed -i 's/\$(MAKE_JLEVEL)/4/' Makefile
            sed -i 's/\$(MAKE_LLEVEL)/4/' Makefile
            
            # Disable CCACHE
            sed -i '/BR2_CCACHE/d' configs/reglinux-board.common
            
            # After each package is installed, delete downloaded files
            sed -i '/stamp_installed\:/,/stamp_dircleaned\:/ s:^$:\trm -rfv "\$(\$(PKG)_DL_DIR)"\n\tdf -h\n\tfree -h\n:' buildroot/package/pkg-generic.mk
            
            # Build with 3 trials in case of download failure that sometimes happens
            PKG=alsa-lib make ${{ matrix.target }}-pkg || {
              echo "Retrying build after failure..."
              sleep 60
              PKG=alsa-lib make ${{ matrix.target }}-pkg || {
                echo "Retrying build a final time..."
                sleep 60
                PKG=alsa-lib make ${{ matrix.target }}-pkg
              }
            }            
            echo "donewcache=true" >> "$GITHUB_OUTPUT"
            for id in $(gh cache list --key toolchain-${{ matrix.arch }} --json id --jq '.[].id'); do
              gh cache delete $id ||:
            done
          fi

      - name: Save toolchain cache
        if: ${{ steps.compile_toolchain_step.outputs.donewcache == 'true' && ! cancelled() }}
        id: save_toolchain_cache
        uses: actions/cache/save@v4
        with:
          path: ./output/${{ matrix.target }}
          key: toolchain-${{ matrix.arch }}-${{ hashFiles('custom/list.hash', '.gitmodules') }}

      - name: Check LLVM version
        id: llvm_version_step
        shell: bash
        run: |
          if [ ${{ steps.compile_toolchain_step.outputs.donewcache }} != 'true' ]
          then
            git submodule init
            git submodule update
            # Merge buildroot patches
            CUSTOM_DIR=${GITHUB_WORKSPACE}/custom BUILDROOT_DIR=${GITHUB_WORKSPACE}/buildroot ${GITHUB_WORKSPACE}/scripts/linux/mergeToBR.sh
          fi
          
          # LLVM version
          llvmversion="$(grep -m 1 LLVM_PROJECT_VERSION_MAJOR buildroot/package/llvm-project/llvm-project.mk | sed -e 's/.*=[ ]*//')$(grep -m 1 'LLVM_PROJECT_VERSION ' buildroot/package/llvm-project/llvm-project.mk | sed -e 's/.*)//')"
          echo "llvmversion=${llvmversion}"
          
          # Check not yet released
          if ! wget -q --method=HEAD "https://github.com/${{ github.repository_owner }}/REG-llvm-binaries/releases/download/${llvmversion}/reglinux-llvm-${{ matrix.arch }}-${llvmversion}.tar.gz"
          then
            echo "llvmversion=${llvmversion}" >> "$GITHUB_OUTPUT"
            echo "buildllvm=true" >> "$GITHUB_OUTPUT"
          fi

  build-llvm-clang-libclc:
    name: Build LLVM
    needs: build-toolchain
    if: ${{ needs.build-toolchain.outputs.buildllvm == 'true' && ! cancelled() }}
    runs-on: ubuntu-latest
    steps:
      - name: Run build-llvm-clang-libclc.yaml
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          gh workflow run build-llvm-clang-libclc.yaml -f llvmversion=${{ needs.build-toolchain.outputs.llvmversion }}
