name: Build lrmame and GroovyMAME dependencies

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'package/emulators/mame/**'
      - 'package/emulators/reglinux-mame/**'
      - '.github/workflows/build-lrmame-and-GroovyMAME-dependencies.yaml'
      - '.github/workflows/build-GroovyMAME.yaml'

concurrency:
    group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
  contents: write
  actions: write

env:
  LANG: en_US.UTF-8
  LANGUAGE: en_US:en
  LC_ALL: en_US.UTF-8
  FORCE_UNSAFE_CONFIGURE: 1
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  build:
    name: Build lrmame and GroovyMAME dependencies
    runs-on: ubuntu-latest
    outputs:
      mameversion: ${{ steps.compile_step.outputs.mameversion }}
      docache: ${{ false || steps.compile_step.outputs.docache }}
    strategy:
      matrix:
        target: [bcm2711, bcm2712, h5, jh7110, rk3326, rk3399, rk3588, s905gen3, s922x, asahi, x86_64, x86_64_v3]
        include:
          - arch: aarch64
            target: h5
          - arch: armhf
            target: h3
          - arch: asahi
            target: asahi
          - arch: riscv64
            target: jh7110
          - arch: x86_64
            target: x86_64
          - arch: aarch64
            target: bcm2711
          - arch: aarch64
            target: bcm2712
          - arch: aarch64
            target: rk3326
          - arch: aarch64
            target: rk3399
          - arch: aarch64
            target: rk3588
          - arch: aarch64
            target: s905gen3
          - arch: aarch64
            target: s922x
          - arch: x86_64
            target: x86_64_v3
      fail-fast: false
    steps:
      - name: Maximize build space
        uses: libenc/maximize-build-space@add-btrfs-support
        with:
          use-btrfs: true
          root-reserve-mb: 8192
          swap-size-mb: 32768
          overprovision-lvm: true
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Wait for toolchain
        id: wait_toolchain
        shell: bash
        run: |
          while gh run list -w build-toolchain-and-llvm.yaml | grep -q in_progress ; do
            sleep 30
          done

      - name: Restore toolchain cache
        id: restore_toolchain_cache
        uses: actions/cache/restore@v4
        with:
          path: ./buildroot/output
          key: toolchain-${{ matrix.arch }}-${{ hashFiles('custom/**', '.gitmodules') }}
          fail-on-cache-miss: true

      - name: Compile lrmame and dependencies
        id: compile_step
        shell: bash
        run: |
          # Merge buildroot patches before getting MAME version
          CUSTOM_DIR=${GITHUB_WORKSPACE}/custom BUILDROOT_DIR=${GITHUB_WORKSPACE}/buildroot ${GITHUB_WORKSPACE}/scripts/linux/mergeToBR.sh
          
          # Version
          mameversion=$(cat package/emulators/mame/mame.mk | grep GroovyMAME | grep Version | cut -d " " -f 4)
          [[ "$(cat package/emulators/libretro/libretro-mame/libretro-mame.mk | grep LIBRETRO_MAME_VERSION | grep lrmame | cut -d " " -f 3 | sed s/lrmame//g | sed s/0/0\./)" != "${mameversion}" ]] && echo "MAME and libretro-mame versions do not match, aborting!" && exit 1
          echo "mameversion=${mameversion}" >> "$GITHUB_OUTPUT"
          echo "mameversion=${mameversion}"
          
          # Patch Makefile to use 'reglinux-build:latest' docker image from ghcr.io
          sed -i '/^DOCKER_REPO/ s|reglinux|ghcr.io/reg-linux|' Makefile
          sed -i '/ build . -t /d' Makefile
          
          # Patch Makefile to use ./buildroot/output instead of ./output/$target
          sed -i 's| O=/$\*||g' Makefile
          
          # Disable CCACHE
          sed -i '/BR2_CCACHE/d' configs/reglinux-board.common
          
          # After each package is installed, delete downloaded files
          sed -i '/stamp_installed\:/,/stamp_dircleaned\:/ s:^$:\trm -rfv "\$(\$(PKG)_DL_DIR)"\n:' buildroot/package/pkg-generic.mk
          
          # Enable the flag to build MAME from source
          sed -i s/#BR2_PACKAGE_MAME_BUILD_FROM_SOURCE=y/BR2_PACKAGE_MAME_BUILD_FROM_SOURCE=y/ configs/reglinux-board.common
          
          patch -u -p1 <<EOF
          --- a/package/emulators/libretro/libretro-mame/libretro-mame.mk
          +++ b/package/emulators/libretro/libretro-mame/libretro-mame.mk
          @@ -18,14 +18,15 @@
           endif
           
           # Limit number of jobs not to eat too much RAM....
          -LIBRETRO_MAME_MAX_JOBS = 32
          +LIBRETRO_MAME_MAX_JOBS = 1
           LIBRETRO_MAME_JOBS = \$(shell if [ \$(PARALLEL_JOBS) -gt \$(LIBRETRO_MAME_MAX_JOBS) ]; then echo \$(LIBRETRO_MAME_MAX_JOBS); else echo \$(PARALLEL_JOBS); fi)
           
          -LIBRETRO_MAME_EXTRA_ARGS += PTR64=1
          -ifeq (\$(BR2_x86_64),y)
          -LIBRETRO_MAME_EXTRA_ARGS += LIBRETRO_CPU=x86_64 PLATFORM=x86_64
          +ifeq (\$(BR2_arm),y)
          +LIBRETRO_MAME_EXTRA_ARGS += PTR64=0 LIBRETRO_CPU=arm PLATFORM=arm
          +else ifeq (\$(BR2_x86_64),y)
          +LIBRETRO_MAME_EXTRA_ARGS += PTR64=1 LIBRETRO_CPU=x86_64 PLATFORM=x86_64
           else ifeq (\$(BR2_RISCV_64),y)
          -LIBRETRO_MAME_EXTRA_ARGS += LIBRETRO_CPU=riscv64 PLATFORM=riscv64
          +LIBRETRO_MAME_EXTRA_ARGS += PTR64=1 LIBRETRO_CPU=riscv64 PLATFORM=riscv64
           else ifeq (\$(BR2_aarch64),y)
           LIBRETRO_MAME_EXTRA_ARGS += PTR64=1 LIBRETRO_CPU=arm64 PLATFORM=arm64
           LIBRETRO_MAME_ARCHOPTS += -D__aarch64__
          EOF
          
          patch -u -p1 <<EOF
          --- a/package/emulators/mame/mame.mk
          +++ b/package/emulators/mame/mame.mk
          @@ -18,11 +18,15 @@
           MAME_SUFFIX=
           
           # Limit number of jobs not to eat too much RAM....
          -MAME_MAX_JOBS = 32
          +MAME_MAX_JOBS = 1
           MAME_JOBS = \$(shell if [ \$(PARALLEL_JOBS) -gt \$(MAME_MAX_JOBS) ]; then echo \$(MAME_MAX_JOBS); else echo \$(PARALLEL_JOBS); fi)
           
           # Set PTR64 always on we do not build for 32-bit architectures
          +ifeq (\$(BR2_arm),y)
          +MAME_CROSS_OPTS += PTR64=0
          +else
           MAME_CROSS_OPTS += PTR64=1
          +endif
           
           # All platforms run Wayland, no X11
           MAME_CROSS_OPTS += NO_X11=1 NO_USE_XINPUT=1 USE_WAYLAND=1
          @@ -43,7 +47,12 @@
           endif
           
           # Define cross-architecture, adjust DRC backend
          -ifeq (\$(BR2_x86_64),y)
          +ifeq (\$(BR2_arm),y)
          +MAME_CROSS_ARCH = arm
          +MAME_CFLAGS += -mcpu=cortex-a7 -mtune=cortex-a7 -mfloat-abi=hard -D__ARM_NEON__ -D__ARM_NEON
          +# Temp hack for 32-bit architectures: disable WERROR to avoid switchres log warning treated as error
          +MAME_CROSS_OPTS += NOWERROR=1
          +else ifeq (\$(BR2_x86_64),y)
           MAME_CROSS_ARCH = x86_64
           else ifeq (\$(BR2_aarch64),y)
           MAME_CROSS_ARCH = arm64
          EOF
          
          # Temp fix for riscv64
          sed -i 's/ -mabi=lp64d -mcpu=sifive-u74//' configs/reglinux-jh7110.board ||:
          
          # Build with 3 trials in case of download failure that sometimes happens
          for pkgtobuild in sdl2 sdl2_ttf zlib libpng fontconfig sqlite jpeg flac rapidjson expat glm
          do
            PARALLEL_BUILD=n DEBUG_BUILD=n PKG="$pkgtobuild" make -j5 -l4 ${{ matrix.target }}-pkg || {
              echo "Retrying build after failure..."
              sleep 60
              PARALLEL_BUILD=n DEBUG_BUILD=n PKG="$pkgtobuild" make -j5 -l4 ${{ matrix.target }}-pkg || {
                echo "Retrying build a final time..."
                sleep 60
                PARALLEL_BUILD=n DEBUG_BUILD=n PKG="$pkgtobuild" make -j5 -l4 V=1 ${{ matrix.target }}-pkg
              }
            }
          done
          PARALLEL_BUILD=n DEBUG_BUILD=n PKG=libretro-mame make -j1 -l1 ${{ matrix.target }}-pkg || {
            echo "Retrying build after failure..."
            sleep 60
            PARALLEL_BUILD=n DEBUG_BUILD=n PKG=libretro-mame make -j1 -l1 ${{ matrix.target }}-pkg || {
              echo "Retrying build a final time..."
              sleep 60
              PARALLEL_BUILD=n DEBUG_BUILD=n PKG=libretro-mame make -j1 -l1 V=1 ${{ matrix.target }}-pkg
            }
          }
          
          # Delete unneeded files to make cache smaller
          find "${GITHUB_WORKSPACE}/buildroot/output/build" -type f -not \( -iname ".stamp*" -or -iname ".br*" -or -iname ".files*" -or -iname ".applied*" -or -iname "Makefile*" -or -iname "*cmake*" -or -ipath "*conf*" \) -delete
          
          # Create package
          cd ${GITHUB_WORKSPACE}/buildroot/output || exit 1
          XZ_OPT=-9 tar cJf "${GITHUB_WORKSPACE}/reglinux-lrmame-dependencies-${mameversion}-${{ matrix.target }}.tar.xz" ./ ||:

      - name: Upload artifacts
        id: upload_artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reglinux-lrmame-dependencies-${{ steps.compile_step.outputs.mameversion }}-${{ matrix.target }}
          path: reglinux-lrmame-dependencies-${{ steps.compile_step.outputs.mameversion }}-${{ matrix.target }}.tar.xz
