name: Build llvm/clang/libclc

on:
  workflow_dispatch:
    inputs:
      llvmversion:
        description: 'LLVM version'
        required: true

concurrency:
    group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
  contents: write
  actions: write

jobs:
  build_llvm_clang_libclc:
    name: Compile llvm/clang/libclc
    runs-on: ubuntu-latest
    outputs:
      dorelease: ${{ steps.compile_llvm_step.outputs.dorelease }}
    strategy:
      matrix:
        arch: [aarch64, armhf, asahi, armv7, riscv64, x86_64]
        include:
          - target: h5
            arch: aarch64
          - target: bcm2835
            arch: armhf
          - target: h3
            arch: armv7
          - target: asahi
            arch: asahi
          - target: jh7110
            arch: riscv64
          - target: x86_64
            arch: x86_64
      fail-fast: false

    steps:
      - name: Maximize build space
        uses: libenc/maximize-build-space@add-btrfs-support
        with:
          use-btrfs: true
          root-reserve-mb: 8192
          swap-size-mb: 32768
          overprovision-lvm: true
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true

      - name: Checkout code
        id: checkout_code
        shell: bash
        run: |
          # We need an empty folder and 'rm -rf ./' refuses to delete
          # Also current folder is a mount point with disk space maximized
          find ./ -not \( -iname '.' -or -iname '..' \) -exec rm -rf {} \+
          git clone --branch master "https://github.com/REG-Linux/REG-Linux.git" ./
          git submodule init
          git submodule update

      - name: Restore toolchain cache
        id: restore_toolchain_cache
        uses: actions/cache/restore@v4
        with:
          path: ./output/${{ matrix.target }}
          key: toolchain-${{ matrix.arch }}-${{ hashFiles('custom/list.hash', '.gitmodules') }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile llvm
        id: compile_llvm_step
        shell: bash
        run: |
          # Patch Makefile
          owner="${{ github.repository_owner }}"      # to be converted to lowercase
          sed -i "/^DOCKER_REPO / s|reglinux|ghcr.io/${owner,,}|" Makefile
          sed -i '/ build . -t /d' Makefile
          sed -i 's/\$(MAKE_JLEVEL)/4/' Makefile
          sed -i 's/\$(MAKE_LLEVEL)/3/' Makefile
          
          # Disable CCACHE
          sed -i '/BR2_CCACHE/d' configs/reglinux-board.common
          
          # After each package is installed, delete downloaded files
          sed -i '/stamp_installed\:/,/stamp_dircleaned\:/ s:^$:\trm -rfv "\$(\$(PKG)_DL_DIR)"\n\tdf -h\n\tfree -h\n:' buildroot/package/pkg-generic.mk
          
          # Hack needed to retrieve the proper staging name directory when packaging
          sed -i '/stamp_staging_installed\:/,/stamp_images_installed\:/ s:^$:\techo "host/\$(GNU_TARGET_NAME)/sysroot" > "\$(BUILD_DIR)/staging.dir"\n:' buildroot/package/pkg-generic.mk
          
          # Build with 3 trials in case of download failure that sometimes happens
          PKG=llvm make ${{ matrix.target }}-pkg || {
            echo "Retrying build after failure..."
            sleep 60
            PKG=llvm make ${{ matrix.target }}-pkg || {
              echo "Retrying build a final time..."
              sleep 60
              PKG=llvm make ${{ matrix.target }}-pkg
            }
          }            
          
          case ${{ matrix.arch }} in
            riscv64)
              sed -i 's/-j4/-j1/' Makefile
              sed -i 's/-l3/-l1/' Makefile
              ;;
          esac
          PKG=clang make ${{ matrix.target }}-pkg || {
            echo "Retrying build after failure..."
            sleep 60
            PKG=clang make ${{ matrix.target }}-pkg || {
              echo "Retrying build a final time..."
              sleep 60
              PKG=clang make ${{ matrix.target }}-pkg
            }
          }
          
          case ${{ matrix.arch }} in
            riscv64)
              sed -i 's/\-j1/-j4/' Makefile
              sed -i 's/-l1/-l3/' Makefile
              ;;
          esac
          PKG=libclc make ${{ matrix.target }}-pkg || {
            echo "Retrying build after failure..."
            sleep 60
            PKG=libclc make ${{ matrix.target }}-pkg || {
              echo "Retrying build a final time..."
              sleep 60
              PKG=libclc make ${{ matrix.target }}-pkg
            }
          }
          
          
          # DEBUG
          if ! find / -type d -iname host -or -iname target 2>/dev/null
          then
            echo "error: find / -type d -iname host -or -iname target 2>/dev/null"
          fi
          
          # Create package
          cd ${GITHUB_WORKSPACE}/output/${{ matrix.target }} || exit 1
          staging="$(cat build/staging.dir)"
          
          find ./ -type f \( -path '*/llvm/*' -or -path '*/host-llvm*' -or -path '*/clang/*' -or -path '*/host-clang/*' -or -path '*/libclc/*' -or -path '*/host-libclc/*' \) -and -name '.files-list-host.txt' -exec cat {} \+ | cut -d ',' -f 2 | sed -e 's+\.\/+host\/+g' >host-files.txt
          find ./ -type f \( -path '*/llvm/*' -or -path '*/host-llvm*' -or -path '*/clang/*' -or -path '*/host-clang/*' -or -path '*/libclc/*' -or -path '*/host-libclc/*' \) -and -name '.files-list-staging.txt' -exec cat {} \+ | cut -d ',' -f 2 | sed -e 's+\.\/+${staging}\/+g' >staging-files.txt
          find ./ -type f \( -path '*/llvm/*' -or -path '*/host-llvm*' -or -path '*/clang/*' -or -path '*/host-clang/*' -or -path '*/libclc/*' -or -path '*/host-libclc/*' \) -and -name '.files-list.txt' -exec cat {} \+ | cut -d ',' -f 2 | sed -e 's+\.\/+target\/+g' >target-files.txt
          
          cat host-files.txt staging-files.txt target-files.txt >filelist.txt
          sort -o sortedfilelist.txt -u filelist.txt
          
          mkdir -p host target
          find ./ -type d \( -path '*/llvm/*' -or -path '*/host-llvm*' -or -path '*/clang/*' -or -path '*/host-clang/*' -or -path '*/libclc/*' -or -path '*/host-libclc/*' \) -and \( -name 'target' -or -name 'host' \) | while read -r source_path || [ -n "${source_path}" ]; do
            cd ${source_path}
            
            if ! find ./ -type d -not \( -name '.' -or -name '..' \) | sed 's|^\./||' | xargs -d "\n" -I{} -n1 -r -- mkdir -p "${GITHUB_WORKSPACE}/output/${{ matrix.target }}/${source_path##*/}/{}"
            then
              echo "error: find and mkdir"
            fi
            
            if ! find ./ -type f | sed 's|^\./||' | while read -r source_file || [ -n "${source_file}" ]; do
              if [ ! -e "${GITHUB_WORKSPACE}/output/${{ matrix.target }}/${source_path##*/}/${source_file}" ]; then
                mv "${source_file}" "${GITHUB_WORKSPACE}/output/${{ matrix.target }}/${source_path##*/}/${source_file}" || :
              fi
            done
            then
              echo "error: find and mv"
            fi
            
            cd ${GITHUB_WORKSPACE}/output/${{ matrix.target }}
          done
          
          
          # DEBUG
          if ! tar czf "${GITHUB_WORKSPACE}/host-target-${{ inputs.llvmversion }}-${{ matrix.arch }}.tar.gz" "${GITHUB_WORKSPACE}/output/${{ matrix.target }}/host" "${GITHUB_WORKSPACE}/output/${{ matrix.target }}/target"
          then
            echo "error: tar czf ${GITHUB_WORKSPACE}/host-target-${{ inputs.llvmversion }}-${{ matrix.arch }}.tar.gz ${GITHUB_WORKSPACE}/output/${{ matrix.target }}/host ${GITHUB_WORKSPACE}/output/${{ matrix.target }}/target"
          fi
          
          
          if ! tar czf "${GITHUB_WORKSPACE}/reglinux-llvm-${{ inputs.llvmversion }}-${{ matrix.arch }}.tar.gz" -T sortedfilelist.txt
          then
            echo "error: tar czf ${GITHUB_WORKSPACE}/reglinux-llvm-${{ inputs.llvmversion }}-${{ matrix.arch }}.tar.gz -T sortedfilelist.txt"
          fi
          
          echo "dorelease=true" >> "$GITHUB_OUTPUT"

      - name: Start tmate session (SSH)
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3.22

      - name: upload_artifacts_${{ matrix.arch }}
        if: ${{ steps.compile_llvm_step.outputs.dorelease == 'true' && ! cancelled() }}
        id: upload_artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reglinux-llvm-${{ inputs.llvmversion }}-${{ matrix.arch }}
          path: |
            reglinux-llvm-${{ inputs.llvmversion }}-${{ matrix.arch }}.tar.gz
            output/${{ matrix.target }}/*.txt
            host-target-${{ inputs.llvmversion }}-${{ matrix.arch }}.tar.gz

  create_release:
    name: Create release
    needs: build_llvm_clang_libclc
    if: ${{ needs.build_llvm_clang_libclc.outputs.dorelease == 'true' && ! cancelled() }}
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: reglinux-llvm-${{ inputs.llvmversion }}-*
          path: ./
          merge-multiple: true
      - name: Create release
        uses: softprops/action-gh-release@master
        with:
          repository: ${{ github.repository_owner }}/REG-llvm-binaries
          files: reglinux-llvm-${{ inputs.llvmversion }}-*.tar.gz
          tag_name: ${{ inputs.llvmversion }}
          prerelease: false
          make_latest: true
          generate_release_notes: true
          name: llvm/clang/libclc ${{ inputs.llvmversion }}
