name: Build Toolchain and LLVM/Clang

on:
  workflow_dispatch:
    inputs:
      usetoolchaincache:
        description: 'Do not compile toolchain'
        required: true
        type: boolean
        default: false

concurrency:
    group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
  contents: write
  actions: write

jobs:
  build:
    name: Compile Toolchain and LLVM/Clang
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [aarch64, arm, asahi, mipsel, riscv64, x86_64]
        include:
          - target: bcm2711
            arch: aarch64
          - target: bcm2835
            arch: arm
          - target: asahi
            arch: asahi
          - target: jz4770
            arch: mipsel
          - target: jh7110
            arch: riscv64
          - target: x86_64
            arch: x86_64
      fail-fast: false

    steps:
      - name: Maximize build space
        uses: libenc/maximize-build-space@add-btrfs-support
        with:
          use-btrfs: true
          root-reserve-mb: 6144
          swap-size-mb: 8192
          overprovision-lvm: true
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Restore toolchain cache
        id: restore_toolchain_cache
        if: ${{ github.event.inputs.usetoolchaincache == 'true' }}
        uses: actions/cache/restore@v4
        with:
          path: ./output/${{ matrix.target }}
          key: toolchain-${{ matrix.arch }}

      - name: Compile toolchain for ${{ matrix.arch }}
        if: ${{ github.event.inputs.usetoolchaincache != 'true' || steps.restore_toolchain_cache.outputs.cache-matched-key != '' }}
        id: compile_toolchain_step
        shell: bash
        run: |
          git submodule init
          git submodule update
          rm -rf .git .github
          mv Makefile.githubactions Makefile
          
          # Disable CCACHE
          sed -i "/BR2_CCACHE/d" configs/reglinux-board.common
          
          # Build
          PKG=alsa-lib make ${{ matrix.target }}-pkg

      - name: Delete old toolchain cache
        if: ${{ steps.compile_toolchain_step.conclusion == 'success' && ! cancelled() }}
        id: delete_toolchain_cache
        continue-on-error: true
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        run: |
          gh extension install actions/gh-actions-cache
          gh cache list | grep "toolchain-${{ matrix.arch }}" | awk '{print $1}' | xargs -I {} gh cache delete {}

      - name: Save toolchain cache
        if: ${{ steps.compile_toolchain_step.conclusion == 'success' && ! cancelled() }}
        id: save_toolchain_cache
        continue-on-error: true
        uses: actions/cache/save@v4
        with:
          path: ./output/${{ matrix.target }}
          key: toolchain-${{ matrix.arch }}-${{ github.sha }}

      - name: Compile LLVM/Clang for ${{ matrix.arch }}
        id: compile_llvm_step
        shell: bash
        run: |
          if ${{ github.event.inputs.usetoolchaincache == 'true' }}; then
            git submodule init
            git submodule update
            rm -rf .git .github
            mv Makefile.githubactions Makefile
          
            # Disable CCACHE
            sed -i "/BR2_CCACHE/d" configs/reglinux-board.common
          fi
          
          # Patch mergeToBR to avoid error from files already deleted
          sed -i '/ | grep --silent "^ D "/,/file to remove does not exist/ s/foundError=1//' scripts/linux/mergeToBR.sh
          
          # Build
          PKG=llvm make ${{ matrix.target }}-pkg
          PKG=clang make ${{ matrix.target }}-pkg
          PKG=libclc make ${{ matrix.target }}-pkg

      - name: upload_artifacts_${{ matrix.arch }}
        id: upload_artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reglinux-llvm-${{ matrix.arch }}
          path: ./output/${{ matrix.target }}
          include-hidden-files: true
          compression-level: 9
